export const ROLES = ['Admin', 'Storekeeper', 'Teacher']
export const STATUSES = ['Active', 'Inactive']
export const ASSIGN_TYPES = ['Department', 'Classroom', 'Teacher']
export const ASSIGN_STATUSES = ['Pending', 'Assigned', 'Completed']
export const PO_STATUSES = ['Draft', 'Sent', 'Approved', 'Partially Received', 'Received', 'Cancelled', 'Closed']
export const RCV_STATUSES = ['Pending', 'Received']
export const RETURN_CONDITIONS = ['Good', 'Damaged']
export const ITEM_CATEGORIES = ['Stationery', 'Furniture', 'ICT', 'Sports', 'Cleaning', 'Other']
